language: go

os:
  - linux
  - osx

go:
  - tip
  - "1.10"

install:
  - go get github.com/issue9/assert
  - go get github.com/issue9/conv

  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
  - go get github.com/lib/pq


script: go test -v -coverprofile=coverage.txt -covermode=atomic $(go list ./...| grep -v /vendor/)

after_success: bash <(curl -s https://codecov.io/bash)
